---
- name: Ensure zabbix sender installed
  apt:
    update_cache: yes
    name: zabbix-sender

- name: ensure discover tasks script exists
  template:
    src: "Discover-CronTasks.ps1.j2"
    dest: "{{ cron_discover_script }}"
    mode: 0740

- name: Creates a cron file under /etc/cron.d without monitoring
  cron:
    name: "{{ item.name }}"
    weekday: "{{ item.weekday | default ('*') }}"
    minute: "{{ item.minute | default ('*') }}"
    hour: "{{ item.hour | default ('*') }}"
    day: "{{ item.day | default ('*') }}"
    month: "{{ item.month | default ('*') }}"
    user: "{{ item.user | default ('root') }}"
    job: "{{ item.job }}"
    cron_file: "{{ item.cron_file | default('ansible_' + item.name) }}"
    state: "{{ item.state | default (omit) }}"
    disabled : "{{ item.disabled  | default (omit) }}"
  with_items:
    - "{{ cron_tasks }}"
  when:
    - cron_tasks is defined
    - item.zabbix_mon is not defined or not item.zabbix_mon
    - item.special_time is not defined
  notify:
    Discover cron tasks

- name: Creates a cron file under /etc/cron.d without monitoring special time
  cron:
    name: "{{ item.name }}"
    weekday: "{{ item.weekday | default ('*') }}"
    minute: "{{ item.minute | default ('*') }}"
    hour: "{{ item.hour | default ('*') }}"
    day: "{{ item.day | default ('*') }}"
    month: "{{ item.month | default ('*') }}"
    user: "{{ item.user | default ('root') }}"
    job: "{{ item.job }}"
    cron_file: "{{ item.cron_file | default('ansible_' + item.name) }}"
    special_time: "{{ item.special_time }}"
    state: "{{ item.state | default (omit) }}"
    disabled : "{{ item.disabled  | default (omit) }}"
  with_items:
    - "{{ cron_tasks }}"
  when:
    - cron_tasks is defined
    - item.zabbix_mon is not defined or not item.zabbix_mon
    - item.special_time is defined
  notify:
    Discover cron tasks

- name: Creates a cron file under /etc/cron.d with monitoring
  cron:
    name: "{{ item.name }}"
    weekday: "{{ item.weekday | default ('*') }}"
    minute: "{{ item.minute | default ('*') }}"
    hour: "{{ item.hour | default ('*') }}"
    day: "{{ item.day | default ('*') }}"
    month: "{{ item.month | default ('*') }}"
    user: "{{ item.user | default ('root') }}"
    job: "{{ item.job }} ; zabbix_sender -z {{ cron_zabbix_server }} -s {{ cron_zabbix_client }} -k trap[{{ item.name }}] -o $? | {{ cron_logger_path }} -t {{ item.tag }}"
    cron_file: "{{ item.cron_file | default('ansible_' + item.name) }}"
    state: "{{ item.state | default (omit) }}"
    disabled : "{{ item.disabled  | default (omit) }}"
  with_items:
    - "{{ cron_tasks }}"
  when:
    - cron_tasks is defined
    - item.zabbix_mon is defined
    - item.zabbix_mon
    - item.special_time is not defined
  notify:
    Discover cron tasks

- name: Creates a cron file under /etc/cron.d with monitoring special time
  cron:
    name: "{{ item.name }}"
    weekday: "{{ item.weekday | default ('*') }}"
    minute: "{{ item.minute | default ('*') }}"
    hour: "{{ item.hour | default ('*') }}"
    day: "{{ item.day | default ('*') }}"
    month: "{{ item.month | default ('*') }}"
    user: "{{ item.user | default ('root') }}"
    job: "{{ item.job }} ; zabbix_sender -z {{ cron_zabbix_server }} -s {{ cron_zabbix_client }} -k trap[{{ item.name }}] -o $? | {{ cron_logger_path }} -t {{ item.tag }}"
    cron_file: "{{ item.cron_file | default('ansible_' + item.name) }}"
    special_time: "{{ item.special_time }}"
    state: "{{ item.state | default (omit) }}"
    disabled : "{{ item.disabled  | default (omit) }}"
  with_items:
    - "{{ cron_tasks }}"
  when:
    - cron_tasks is defined
    - item.zabbix_mon is defined
    - item.zabbix_mon
    - item.special_time is defined
  notify:
    Discover cron tasks