---
- name: Ensure zabbix sender installed
  apt:
    name: zabbix-sender

- name: ensure discover tasks script exists
  template:
    src: "Discover-CronTasks.ps1.j2"
    dest: "{{ cron_discover_script }}"
    mode: 0740
  notify:
    Discover cron tasks

- name: Creates SHELL varible in a cron file under /etc/cron.d
  cron:
    name: SHELL
    env: yes
    job: /bin/bash
    user: "{{ item.user | default('root') }}"
    cron_file: "{{ item.cron_file | default('ansible_' + item.name) }}"
  with_items:
    - "{{ cron_tasks }}"
  when:
    - (item.zabbix_mon | default(cron_zabbix_monitor_jobs_default))
  notify:
    Discover cron tasks

- name: Creates a cron file under /etc/cron.d without monitoring
  cron:
    name: "{{ item.name }}"
    weekday: "{{ item.weekday | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    user: "{{ item.user | default('root') }}"
    job: "{{ item.job }}"
    cron_file: "{{ item.cron_file | default('ansible_' + item.name) }}"
    state: "{{ item.state | default(omit) }}"
    disabled : "{{ item.disabled  | default(omit) }}"
  with_items:
    - "{{ cron_tasks }}"
  when:
    - not (item.zabbix_mon | default(cron_zabbix_monitor_jobs_default))
    - item.special_time is not defined
  notify:
    Discover cron tasks

- name: Creates a cron file under /etc/cron.d without monitoring special time
  cron:
    name: "{{ item.name }}"
    weekday: "{{ item.weekday | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    user: "{{ item.user | default('root') }}"
    job: "{{ item.job }}"
    cron_file: "{{ item.cron_file | default('ansible_' + item.name) }}"
    special_time: "{{ item.special_time }}"
    state: "{{ item.state | default(omit) }}"
    disabled : "{{ item.disabled  | default(omit) }}"
  with_items:
    - "{{ cron_tasks }}"
  when:
    - not (item.zabbix_mon | default(cron_zabbix_monitor_jobs_default))
    - item.special_time is defined
  notify:
    Discover cron tasks

- name: Creates a cron file under /etc/cron.d with monitoring
  cron:
    name: "{{ item.name }}"
    weekday: "{{ item.weekday | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    user: "{{ item.user | default('root') }}"
    job: >
      zabbix_sender -z {{ cron_zabbix_server }} -s {{ cron_zabbix_client }} -k trap[{{ item.name }}] -o "-1.0" ;
      {{ item.job }} | {{ cron_logger_path }} -t {{ item.tag }} ;
      zabbix_sender -z {{ cron_zabbix_server }} -s {{ cron_zabbix_client }} -k trap[{{ item.name }}] -o ${PIPESTATUS[0]}
    cron_file: "{{ item.cron_file | default('ansible_' + item.name) }}"
    state: "{{ item.state | default(omit) }}"
    disabled : "{{ item.disabled  | default(omit) }}"
  with_items:
    - "{{ cron_tasks }}"
  when:
    - (item.zabbix_mon | default(cron_zabbix_monitor_jobs_default))
    - item.special_time is not defined
  notify:
    Discover cron tasks

- name: Creates a cron file under /etc/cron.d with monitoring special time
  cron:
    name: "{{ item.name }}"
    weekday: "{{ item.weekday | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    user: "{{ item.user | default('root') }}"
    job: >
      zabbix_sender -z {{ cron_zabbix_server }} -s {{ cron_zabbix_client }} -k trap[{{ item.name }}] -o "-1.0" ;
      {{ item.job }} | {{ cron_logger_path }} -t {{ item.tag }} ;
      zabbix_sender -z {{ cron_zabbix_server }} -s {{ cron_zabbix_client }} -k trap[{{ item.name }}] -o ${PIPESTATUS[0]}
    cron_file: "{{ item.cron_file | default('ansible_' + item.name) }}"
    special_time: "{{ item.special_time }}"
    state: "{{ item.state | default(omit) }}"
    disabled : "{{ item.disabled  | default(omit) }}"
  with_items:
    - "{{ cron_tasks }}"
  when:
    - (item.zabbix_mon | default(cron_zabbix_monitor_jobs_default))
    - item.special_time is defined
  notify:
    Discover cron tasks